modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
version="${version}"
authors="manmaed"
# Change This Stuff below
modId="petrock"
displayName="PetRock"
#issueTrackerURL="http://my.issue.tracker/"
# The description text for the mod (multi line!)
description='''
A Mod that adds PetRocks!
'''
# End
